# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a568965505892c498eaef44b9c41d24eff71a3c245653e8c9d77bd94b4dc1e105c6e5fb8d3bb898e8aea21c261b39b96e54d03114e3077ee371d21625bb84858

test:
  secret_key_base: 1d10705e0eea697521b588febb8402c911bd5d13924407ace32ecd027be1442e03423c2ae774494871208b03068cf85656bf8165ed19036bec83f93a3a927c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
